include::.settings.adoc[]

:docinfo: shared

== Plugins

=== Plugins

For uses plugins, you should https://docs.asciidoctor.org/asciidoc/latest/docinfo/#enable[enable docinfo]
and create file `docinfo-footer.html`

[source, markdown]
----
:docinfo: shared
----

.docinfo-footer.html
[source, html]
----
<script src="./../javascripts/reveal.js/plugin/mermaid/mermaid.js"></script>
<script src="./../javascripts/reveal.js/plugin/copycode/copycode.js"></script>
<script>
    Reveal.configure({
        // mermaid: {},
        // copycode: {},
    })
    Reveal.registerPlugin(RevealMermaid)
    Reveal.registerPlugin(CopyCode)
</script>
----

== Diagram

=== Diagram

We use https://mermaid.js.org/[mermaid engine] to render diagrams, charts, etc.

[.mermaid]
....
graph LR
    A[Square Rect] -- Link text --> B((Circle))
    A --> C(Round Rect)
    B --> D{Rhombus}
    C --> D
....

=== Diagram: pie chart

[.mermaid]
....
%%{init: {"pie": {"textPosition": 0.5}, "themeVariables": {"pieOuterStrokeWidth": "5px"}} }%%
pie showData
    title Key elements in Product X
    "Calcium" : 42.96
    "Potassium" : 50.05
    "Magnesium" : 10.01
    "Iron" :  5
....

[source, markdown]
----
[.mermaid]
....
%%{init: {"pie": {"textPosition": 0.5}, "themeVariables": {"pieOuterStrokeWidth": "5px"}} }%%
pie showData
    title Key elements in Product X
    "Calcium" : 42.96
    "Potassium" : 50.05
    "Magnesium" : 10.01
    "Iron" :  5
....
----

=== Diagram: sequence

[.mermaid]
....
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>Bob: Hello Bob, how are you?
    Bob-->>Alice: Great!
....

[source, markdown]
----
[.mermaid]
....
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>Bob: Hello Bob, how are you?
    Bob-->>Alice: Great!
....
----

=== Diagram: graph

[.mermaid]
....
graph LR
    s([Source]) --> a[[aquamarine]]
    r[[rustdoc]] --> f([Docs w/ Mermaid!])
    subgraph rustc[Rust Compiler]
    a -. inject mermaid.js .-> r
    end
....


[source, markdown]
----
[.mermaid]
....
graph LR
    s([Source]) --> a[[aquamarine]]
    r[[rustdoc]] --> f([Docs w/ Mermaid!])
    subgraph rustc[Rust Compiler]
    a -. inject mermaid.js .-> r
    end
....
----

=== Diagram: git graph

[.mermaid]
....
---
title: Example Git diagram
---
gitGraph
   commit
   commit
   branch develop
   checkout develop
   commit
   commit
   checkout main
   merge develop
   commit
   commit
....

[.small]
[source, markdown]
----
[.mermaid]
....
---
title: Example Git diagram
---
gitGraph
   commit
   commit
   branch develop
   checkout develop
   commit
   commit
   checkout main
   merge develop
   commit
   commit
....
----